name: Ecobici Stations Jobs

on:  # events that trigger this workflow: schedule and workflow_dispatch
  schedule:
    - cron: '14-59/30 * * * *'
  workflow_dispatch:  # when empty, adds a button for manual triggering

permissions:
  contents: write

jobs:
  sample-ecobici-stations:
    name: Sample Ecobici stations
    #if: github.ref == 'refs/heads/main'  # to run only on that branch
    runs-on: ubuntu-latest
    env:
      TRANSPORT_BA_CLIENT_ID: ${{ secrets.TRANSPORT_BA_CLIENT_ID }}
      TRANSPORT_BA_SECRET: ${{ secrets.TRANSPORT_BA_SECRET }}
      HEIGIT_OPENROUTESERVICE_API_KEY: ${{ secrets.HEIGIT_OPENROUTESERVICE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - run: pip install requests pandas typer
      - run: python cli.py sample-ecobici-stations
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add data/stations.csv
          git commit -m "Append stations.csv rows" || true
          git push

  update-ecobici-stations-durations:
    name: Update Ecobici stations durations from OpenRouteService
    #if: github.ref == 'refs/heads/main'  # to run only on that branch
    runs-on: ubuntu-latest
    env:
      TRANSPORT_BA_CLIENT_ID: ${{ secrets.TRANSPORT_BA_CLIENT_ID }}
      TRANSPORT_BA_SECRET: ${{ secrets.TRANSPORT_BA_SECRET }}
      HEIGIT_OPENROUTESERVICE_API_KEY: ${{ secrets.HEIGIT_OPENROUTESERVICE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - run: pip install requests pandas typer
      - run: python cli.py update-ecobici-stations-durations
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase
          git add data/journeys.csv
          git commit -m "Update journeys.csv if changes found" || true
          git push
